### ISSUE TITLE
add support for local templates

### ISSUE THREAD

**Issue by NPetz** [recursiveai/ganzo#1]
when developing new templates for https://github.com/recursiveai/tenpureto , we want to try them out to make sure they work when downloaded with ganzo.

But development is hindered by the fact that the templates to function properly need to have some parts of it "resolved", like `pyproject.toml.nzo` file.

By adding support to loading local templates with ganzo, we can simulate the resolution of the templates without first having to upload them to the cloud.

**Comment by miguelnmiranda** [comment]
As of version `0.2.1` gonzo can also handle templates defined locally.
